### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by pashadag** [jermp/data_compression_course#5]
list_compressor pdf, Elias-Fano slide, 
"The high bits are clustered together and written in unary in another bit-vector high_bits."

It took me awhile to get this, I would have stated this as: 
"The high bits are clustered together and *the size of each cluster* written in unary in another bit-vector high_bits."

(let me know if this is the best way to leave feedback or something else is better. I'm enjoying learning from your slides!)

**Comment by jermp** [comment]
Hi Paul,
you're absolutely right: it is, of course, the **size** of each cluster that is written in unary.
I'm correcting this, thank you very much.

I'm very happy you're finding this material useful and I'm more than happy if you report here some feedback!
As you have seen, I tried to introduce topics in an informal but pleasant way -- with a bit less care for formality.
I haven't revised the material in a while, so it is possible that you find some typos or bugs in some definitions.

Please let me know!
Best,
-Giulio

**Comment by pashadag** [comment]
Thank Giulio. The slides are perfect for me...they introduce the key idea that I can get very quickly. For details, if I don't get it from the slides, I know where to look.

**Comment by jermp** [comment]
Thank you Paul, this is exactly the purpose of the course.
Feel free to open other issues here. Very appreciated!
